@Sustema.Api_HostAddress = http://localhost:5263

GET {{Sustema.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Sustema.Api_HostAddress}}/api/User/all
Accept: application/json

###
@id=1
GET {{Sustema.Api_HostAddress}}/api/user/{{id}}
Accept: application/json
###

POST {{Sustema.Api_HostAddress}}/api/user/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJ1c2VyQGV4YW1wbGUuY29tIiwicm9sZSI6IkNpZGFkYW8iLCJuYmYiOjE3NDI3NjM1MTMsImV4cCI6MTc0Mjc2NzExMywiaWF0IjoxNzQyNzYzNTEzLCJpc3MiOiJZb3VySXNzdWVyIiwiYXVkIjoiWW91ckF1ZGllbmNlIn0.TszAvIFhSPOueFdi-D-cFCqUD8GdgFTgBd4duAlPoME
Content-Type: application/json

{
  "nome": "Fulano de Tal",
  "email": "teste2@gmail.com",
  "password": "Senha123",
  "perfil": 0
}

###
