@Sustema.Api_HostAddress = http://localhost:5263

GET {{Sustema.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Sustema.Api_HostAddress}}/api/User/all
Accept: application/json

###
@id=1
GET {{Sustema.Api_HostAddress}}/api/user/{{id}}
Accept: application/json
###

POST {{Sustema.Api_HostAddress}}/api/user/register
Authorization: Bearer JWT_TOKEN_HERE
Content-Type: application/json

{
  "nome": "Fulano de Tal",
  "email": "teste2@gmail.com",
  "password": "Senha123",
  "perfil": 0
}

###

GET {{Sustema.Api_HostAddress}}/api/User/perfil-usuarios

###

GET {{Sustema.Api_HostAddress}}/api/EducationalContent/tipos

###
GET {{Sustema.Api_HostAddress}}/api/educationalcontent

###

GET {{Sustema.Api_HostAddress}}/api/educationalcontent/{{id}}

###

GET {{Sustema.Api_HostAddress}}/api/collectionpoint

###

GET {{Sustema.Api_HostAddress}}/api/collectionpoint/{{id}}

###
