version: '3.8'
services:
  backend:
    build:
      context: ./backend/Sustema.Api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:5001"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Sustema123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

volumes:
  sqlserverdata: